export const pronouns = [
  ["she", "her", "her", "hers", "herself"],
  ["he", "him", "his", "his", "himself"],
  ["they", "them", "their", "theirs", "themself"],
  ["ze", "hir", "hir", "hirs", "hirself"],
  ["ze", "zir", "zir", "zirs", "zirself"],
  ["xey", "xem", "xyr", "xyrs", "xemself"],
  ["ae", "aer", "aer", "aers", "aerself"],
  ["e", "em", "eir", "eirs", "emself"],
  ["ey", "em", "eir", "eirs", "eirself"],
  ["fae", "faer", "faer", "faers", "faerself"],
  ["fey", "fem", "feir", "feirs", "feirself"],
  ["hu", "hum", "hus", "hus", "humself"],
  ["it", "it", "its", "its", "itself"],
  ["jee", "jem", "jeir", "jeirs", "jemself"],
  ["kit", "kit", "kits", "kits", "kitself"],
  ["ne", "nem", "nir", "nirs", "nemself"],
  ["peh", "pehm", "peh's", "peh's", "pehself"],
  ["per", "per", "per", "pers", "perself"],
  ["sie", "hir", "hir", "hirs", "hirself"],
  ["se", "sim", "ser", "sers", "serself"],
  ["shi", "hir", "hir", "hirs", "hirself"],
  ["si", "hyr", "hyr", "hyrs", "hyrself"],
  ["they", "them", "their", "theirs", "themselves"],
  ["thon", "thon", "thons", "thons", "thonself"],
  ["ve", "ver", "vis", "vis", "verself"],
  ["ve", "vem", "vir", "virs", "vemself"],
  ["vi", "ver", "ver", "vers", "verself"],
  ["vi", "vim", "vir", "virs", "vimself"],
  ["vi", "vim", "vim", "vims", "vimself"],
  ["xie", "xer", "xer", "xers", "xerself"],
  ["xe", "xem", "xyr", "xyrs", "xemself"],
  ["xey", "xem", "xeir", "xeirs", "xemself"],
  ["yo", "yo", "yos", "yos", "yosself"],
  ["ze", "zem", "zes", "zes", "zirself"],
  ["ze", "mer", "zer", "zers", "zemself"],
  ["zee", "zed", "zeta", "zetas", "zedself"],
  ["zie", "zir", "zir", "zirs", "zirself"],
  ["zie", "zem", "zes", "zes", "zirself"],
  ["zie", "hir", "hir", "hirs", "hirself"],
  ["zme", "zmyr", "zmyr", "zmyrs", "zmyrself"],
];

export const sexualities = [
  "Abroromantic",
  "Abrosexual",
  "Achillean",
  "Agender",
  "Alloromantic Asexual",
  "Ambiamorous",
  "Anarcha-Queer",
  "Androgyne",
  "Androsexual",
  "Aporagender",
  "Archaeopronouns",
  "Aroace",
  "Aromantic Allosexual",
  "Aromantic",
  "Asexual",
  "Autigender",
  "Bear",
  "Bicurious",
  "Bigender",
  "Biromantic",
  "Bisexual",
  "Butch",
  "Ceteroromantic",
  "Ceterosexual",
  "Cis Ally",
  "Demiboy",
  "Demigender",
  "Demigirl",
  "Demiromantic",
  "Demisexual",
  "Diamoric",
  "Enbian",
  "Fa'afafine",
  "Femme",
  "Gay",
  "Gender Questioning",
  "Genderdoe",
  "Genderfae",
  "Genderfaun",
  "Genderfluid",
  "Genderflux",
  "Genderqueer",
  "Greyaromantic",
  "Greyasexual",
  "Gynesexual",
  "Heteroflexible",
  "Heteroromantic",
  "Heterosexual",
  "Hijra",
  "Homoflexible",
  "Homoromantic",
  "Intersex",
  "Leather Pride",
  "Lesbian",
  "Lesbiromantic",
  "LGBTQ",
  "Maverique",
  "Monoamorous",
  "Monogamous",
  "Muxe",
  "Nebularomantic",
  "Neopronouns",
  "Neutrois",
  "Nonbinary",
  "Omniromantic",
  "Omnisexual",
  "Oriented Aroace",
  "Pangender",
  "Panromantic",
  "Pansexual",
  "Polyamorous",
  "Polyromantic",
  "Polysexual",
  "Pomoromantic",
  "Pomosexual",
  "Progress Pride",
  "Queer",
  "Queerian",
  "Queerplatonic",
  "Quoiromantic",
  "Sapphic",
  "Sexuality Questioning",
  "Straight Ally",
  "Toric",
  "Transfeminine",
  "Transgender",
  "Transmasculine",
  "Transneutral",
  "Trigender",
  "Trixic",
  "Two Spirit",
  "Xenogender",
];

export const personalities = [
    'ISTJ',
    'ESTJ',
    'ISFJ',
    'ESFJ',
    'ESFP',
    'ISFP',
    'ESTP',
    'ISTP',
    'INFJ',
    'ENFJ',
    'INFP',
    'ENFP',
    'INTP',
    'ENTP',
    'INTJ',
    'ENTJ',
]